INSERT INTO previoustest (previoustest_name) VALUES ('카카오 신입 공채')
INSERT INTO previoustest (previoustest_name) VALUES ('카카오 인턴십')
INSERT INTO previoustest (previoustest_name) VALUES ('카카오 코드 페스티벌')
INSERT INTO previoustest (previoustest_name) VALUES ('삼성 신입 공채')
INSERT INTO previoustest (previoustest_name) VALUES ('서울대학교 SCSC 프로그래밍 경시대회')
INSERT INTO previoustest (previoustest_name) VALUES ('네이버 코딩 테스트 기출')
INSERT INTO previoustest (previoustest_name) VALUES ('COS pro 2급')
INSERT INTO previoustest (previoustest_name) VALUES ('COS pro 1급')

INSERT INTO language (language_name) VALUES ('Java')
INSERT INTO language (language_name) VALUES ('JavaScript')
INSERT INTO language (language_name) VALUES ('Python')
INSERT INTO language (language_name) VALUES ('C')
INSERT INTO language (language_name) VALUES ('C++')
INSERT INTO language (language_name) VALUES ('C#')
INSERT INTO language (language_name) VALUES ('Go')
INSERT INTO language (language_name) VALUES ('Kotlin')