INSERT INTO algorithm (algorithm_name) VALUES ('수학')
INSERT INTO algorithm (algorithm_name) VALUES ('구현')
INSERT INTO algorithm (algorithm_name) VALUES ('자료 구조')
INSERT INTO algorithm (algorithm_name) VALUES ('문자열')
INSERT INTO algorithm (algorithm_name) VALUES ('그리드 알고리즘')
INSERT INTO algorithm (algorithm_name) VALUES ('정렬')
INSERT INTO algorithm (algorithm_name) VALUES ('이분 탐색')
INSERT INTO algorithm (algorithm_name) VALUES ('사칙 연산')
INSERT INTO algorithm (algorithm_name) VALUES ('누적 합')
INSERT INTO algorithm (algorithm_name) VALUES ('재귀')

INSERT INTO difficulty (difficulty_name) VALUES ('Easy')
INSERT INTO difficulty (difficulty_name) VALUES ('Normal')
INSERT INTO difficulty (difficulty_name) VALUES ('Hard')
INSERT INTO difficulty (difficulty_name) VALUES ('Extreme')
